name: Publish Spark metadata client
on:
  workflow_dispatch:
jobs:
  publish-spark-metadata-client:
    name: Publish Spark metadata client
    runs-on: ubuntu-20.04
    environment: Treeverse signing
    steps:
      - name: Check-out code
        uses: actions/checkout@v2

      - name: Setup Scala
        uses: olafurpg/setup-scala@v10

      - name: Validate format
        working-directory: clients/spark
        run: sbt scalafmtCheck

      - name: Validate unused
        working-directory: clients/spark
        run: sbt scalafix --check

      - name: Install secret key for signing
        run: |
          echo -e '${{ secrets.OSSRH_GPG_SECRET_KEY }}' | gpg --batch --import
          gpg --list-secret-keys --keyid-format LONG

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}

      - name: Prepare publish credentials
        run: |
          mkdir -p ~/.sbt
          cat << EOS > ~/.sbt/credentials
          realm=Amazon S3
          host=treeverse-clients-us-east.s3.amazonaws.com
          EOS
          cat << EOS > ~/.sbt/sonatype_credentials
          realm=Sonatype Nexus Repository Manager
          host=s01.oss.sonatype.org
          user=${OSSRH_USERNAME}
          password=${OSSRH_TOKEN}
          EOS
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}

      - name: Publish artifacts
        run: make publish-scala-test # TODO(barak): temporary using test
        env:
          AWS_REGION: us-east-1
          AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}

